### ISSUE TITLE
ArgumentOutOfRangeException in Roler.Toolkit.File.Mobi.Compression.PalmDocCompression.Decompress

### ISSUE THREAD

**Issue by stpatrick2016** [rolerzhang/RolerFileToolkit#1]
Hey, first of all - nice work :) Opens most of the books I have. There are very few where I get an index out of range exception coming with this call stack:

>    at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at Roler.Toolkit.File.Mobi.Compression.PalmDocCompression.Decompress(Byte[] bytes)
   at Roler.Toolkit.File.Mobi.MobiReader.ReadText(Structure structure)
   at Roler.Toolkit.File.Mobi.MobiReader.Read()

Attaching [one](https://github.com/rolerzhang/RolerFileToolkit/files/4902542/Kanningem_M._Snejnaya_Koroleva.mobi.zip) of such files for reproduction (zipped). The code is the simplest one:
```csharp
using (var f = File.OpenRead(file_to_file))
{
    using (var mobiReader = new MobiReader(f))
    {
        var mobi = mobiReader.Read();
//...
```
Thanks and keep it up :)

**Comment by rolerzhang** [comment]
Hello, thank you for opening an issue.
I will fix this problem in the next update. soon

**Comment by rolerzhang** [comment]
[Roler.Toolkit.File.Mobi 1.0.1](https://www.nuget.org/packages/Roler.Toolkit.File.Mobi) published.
